pool:
  name: Azure Pipelines
steps:
- task: PythonScript@0
  displayName: 'Run a Python script'
  inputs:
    scriptSource: inline
    script: |
     import subprocess
     
     print("Salem")
     cmd = 'az vm image list'
     completed_process = subprocess.run(cmd, shell=True, capture_output=True)
     if completed_process.stderr:
                     print("Something went wrong while executing the az command!\nStd Error: {0}\n".format(str(completed_process.stderr)))
                     print("="*100,"\n")
     print("Done")
